remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    github: jadistanbelly
    linkedin: jadistanbelly
    telegram: jadistanbelly
header_pages:
  - About.md
  - Projects.md
author:
  name: Jad Istanbelly
  email: "jadelkareem@hotmail.com"
title: Jad Istanbelly
description: Bookmark this to keep an eye on my projects!
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
